/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'm.lataix' at '19/03/18 13:51' with Gradle 3.0
 *
 * @author m.lataix, @date 19/03/18 13:51
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
